
-------------------USERS----------------------------
INSERT INTO SHSTROL(NAME, STATUS, CREATEDDATE, VERSION)
VALUES('ADMIN', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPERSON (DNI, NAME, LASTNAME, EMAIL, STATUS, CREATEDDATE, VERSION)
values ('123456', 'Oscar', 'Viana', 'oscar.viana@hotmail.com', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTUSER(ROLID, PERSONID, USERNAME, PASSWORD, STATUS, CREATEDDATE, VERSION)
VALUES(1, 1, 'admin', '$2a$04$.KWzIdnYsXl2G7EXMuE3Ue7XE26/lelFLB3A161WyJ.UfevsbXpUe', '1', CURRENT_TIMESTAMP, 0);



------------------CATEGORY---------------------------
INSERT INTO SHSTCATEGORYTYPE(NAME, STATUS, CREATEDDATE, VERSION)
VALUES ('Marvel', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTCATEGORYTYPE(NAME, STATUS, CREATEDDATE, VERSION)
VALUES ('DC Comics', '1', CURRENT_TIMESTAMP, 0);


-----MARVEL---------------
INSERT INTO SHSTCATEGORY(CATEGORYTYPEID, NAME, DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES (1, 'Camisetas', 'Camisetas', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTCATEGORY(CATEGORYTYPEID, NAME, DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES (1, 'Vasos', 'Vasos', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTCATEGORY(CATEGORYTYPEID, NAME, DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES (1, 'Comics', 'Comics', '1', CURRENT_TIMESTAMP, 0);


-----DC COMICS---------------

INSERT INTO SHSTCATEGORY(CATEGORYTYPEID, NAME, DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES (2, 'Juguetes', 'Juguetes', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTCATEGORY(CATEGORYTYPEID, NAME, DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES (2, 'Accesorios', 'Accesorios', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTCATEGORY(CATEGORYTYPEID, NAME, DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES (2, 'Otros', 'Otros', '1', CURRENT_TIMESTAMP, 0);


------------------------PRODUCTOS--------------------------

INSERT INTO SHSTPAYMENTTYPE(DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES ('Trasnferencia bancaria', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPAYMENTTYPE(DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES ('Tarjeta de credito', '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPAYMENTTYPE(DESCRIPTION, STATUS, CREATEDDATE, VERSION)
VALUES ('Pago en efectivo', '1', CURRENT_TIMESTAMP, 0);


INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (1,'654321', 'Camiseta IronMan', '', 10, 50, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (2,'654322', 'Vaso IronMan Kids', '', 5, 5, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (3,'654323', 'The last adventure Spiderman - Comic', '', 7, 7, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (4,'654324', 'Mini Superman Lego', '', 20, 2, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (4,'664321', 'Juguete Batman', '', 10, 50, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (5,'664322', 'Mascara Flash', '', 5, 5, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (3,'664323', 'The last adventure Wolverice - Comic', '', 7, 7, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (4,'664324', 'Mini Aquaman forever', '', 20, 2, '1', CURRENT_TIMESTAMP, 0);